### ISSUE TITLE
Is this package already operational?

### ISSUE THREAD

**Issue by slakbal** [thephpleague/commonmark-ext-table#1]
Wondering if this is working already?

**Comment by hason** [comment]
Yes, it's a functional version. I want to release the first tagged version in next week.

**Comment by bcremer** [comment]
Can confirm that it's working. 
We use it on [developers.shopware.com](https://github.com/shopware/devdocs/blob/master/composer.json#L12) in production.
I would like to see a tagged version nevertheless.

**Comment by hason** [comment]
I have created the first tagged version `0.1.0`.
