### ISSUE TITLE
Set a class to the <table> element

### ISSUE THREAD

**Issue by Xety** [thephpleague/commonmark-ext-table#10]
Hello,
Can we set a class name to the `<table>` element by default ?
If yes, how please ?

**Comment by hason** [comment]
You should use https://github.com/webuni/commonmark-attributes-extension:

```markdown
h         | h 
----------|---
c1        | c2
{.class1 style="color:red" border=3 width="50%}
```
If you want to add a class name for all tables by default, you can register a custom extension with own table renderer https://github.com/webuni/commonmark-table-extension/blob/master/src/TableExtension.php#L29.

**Comment by Xety** [comment]
I will go for the second option, because i want it on all tables by default.
Thanks for your fast answer !

**Comment by egorsmkv** [comment]
@Xety do you have any solution for your task?
