### ISSUE TITLE
Conflict between colons and tables

### ISSUE THREAD

**Issue by mlpadilla** [thephpleague/commonmark-ext-table#2]
Hi,

I have spotted an issue in [Daux.io](https://github.com/justinwalsh/daux.io) which uses your library and I have
been asked to report it here.

It seems that there is a problem when parsing colons before a table. 

Please have a look at the following example

```
text1

:

| a | b |
| --- | --- |
| 1 | 2 |

text2
```

The table is not formatted correctly, and everything before the second dash
separator is truncated.

If I use the HTML entity for colon, it works fine:

```
text1

&#58;

| a | b |
| --- | --- |
| 1 | 2 |

text2
```

Also, a colon after the table works correctly:

```
text1

| a | b |
| --- | --- |
| 1 | 2 |

:

text2
```

Thanks

**Comment by hason** [comment]
@mlpadilla I can not reproduce the issue. Generated html with the newest version (0.4.3) is correct:

``` html
<p>text1</p>
<p>:</p>
<table>
<thead>
<tr>
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>
<p>text2</p>
```

**Comment by mlpadilla** [comment]
Hi @hason.

That output seems correct. I downloaded de latest version of Daux.io and it seems to be using version 0.4.3 of your library:

https://github.com/justinwalsh/daux.io/blob/master/composer.lock

However, Daux.io is still failing to display the table. From this example:

```
text1

:

| a | b |
| --- | --- |
| 1 | 2 |

text2
```

This is the output I get:

``` html
    <p>| --- |
| 1 | 2 |</p>
<p>text2</p>
```

If you are sure your library is working fine, would you mind mentioning it here?
https://github.com/justinwalsh/daux.io/issues/345

Thanks

**Comment by hason** [comment]
@mlpadilla I tested daux documentation with mentioned example and all is alright. So I close this issue.
![daux-table](https://cloud.githubusercontent.com/assets/288535/13673251/861a37fe-e6d8-11e5-9001-7e0d09d62b7b.png)

**Comment by mlpadilla** [comment]
Hi @hason . Thanks for having a look. I have tried your same example and works. However, it does not work in other occasions.

On the same document you edited (GitHub_Flavored_Markdown.md), if the text is placed at the beginning of the document, it fails:
![text before header](https://cloud.githubusercontent.com/assets/10867537/13795856/529e2a62-eafb-11e5-98f4-6d981d957d45.png)
If placed after the header, it's displayed correctly:
![text after header](https://cloud.githubusercontent.com/assets/10867537/13795874/62f07e60-eafb-11e5-95ee-a4a9d2e5717b.png)

**Comment by hason** [comment]
@mlpadilla Thank you for reporting.

**Comment by hason** [comment]
@mlpadilla Sorry, but problem is in daux.io code (see https://github.com/justinwalsh/daux.io/issues/345#issuecomment-232683133).
