### ISSUE TITLE
Move to the PHP League?

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark-ext-table#25]
Hey @hason,

We're looking to make `league/commonmark-extras` be fully compatible with GFM.  We have pretty much everything we need except for table functionality.

**Would you have any interest in bringing this project into the PHP League as `league/commonmark-ext-tables`?**  If so, I'd be happy to have you as a co-maintainer!

Bringing this into the League could offer several advantages:

 - It'll be easier to keep this up-to-date, especially with work being done in the core engine
    - We did this for our other official extensions - everything was ready on the release date
 - More maintainers = faster issue remediation
 - We can bring it into the `league/commonmark-extras` meta-package, thus greatly increasing the number of people using this

I'd be willing to do virtually all of the work to change the namespace, add to Packagist, etc.  We did this with another community extension (the strikethrough one) and that seemed to go really well, so I'd like to offer you that same opportunity if you're interested.  The only bit I'd really need from you is marking the current package as deprecated once everything has been moved over.

Just let me know! :)

**Comment by hason** [comment]
@colinodell I agree. How are we going to proceed? Should I move this repository to phpleague organization?

**Comment by colinodell** [comment]
Awesome!  So we basically have two options:

1. Move the repository into the phpleague organization
2. Fork this into the phpleague organization

I'd prefer option 1, as it'll retain all of the issue and PR history. All existing links to this project would also redirect to the new location.

So when you get a moment, go ahead and initiate the transfer request to https://github.com/thephpleague.  I can then approve the transfer and re-elevate your permissions on the project to be a maintainer so you can continue with the usual maintainer duties (as little or much as you'd like).

**Comment by hason** [comment]
@colinodell Should I rename repository to `commonmark-ext-table`?

**Comment by colinodell** [comment]
Yeah that name sounds good to me.

**Comment by hason** [comment]
@colinodell Github did not transfer the repository: `You don’t have the permission to create repositories on thephpleague`

**Comment by hason** [comment]
@colinodell You are admin for this repository. Can you transfer it to thephpleague organization?

**Comment by colinodell** [comment]
Ah okay, yes, I will do that now!

**Comment by colinodell** [comment]
It has been moved! :tada: I can start working on the namespace stuff now.

**Comment by colinodell** [comment]
This project has been moved to `league/commonmark-ext-table`!

All existing versions use the `Webuni\CommonMark\TableExtension` namespace.  We'll get a brand new `2.0.0` release out soon using the `League\CommonMark\Ext\Table` namespace and then bundle this library into the next release of `league/commonmark-extras`

I look forward to working with you on this project @hason!
