### ISSUE TITLE
caption and table id

### ISSUE THREAD

**Issue by renanbr** [thephpleague/commonmark-ext-table#3]
Table caption isn't a part of MD standard, but it would be great if (optionally) we are able to define it (and table id too). Do you intend to allow **optional** non-standard syntax?

A possible approach is to get information like https://github.com/fletcher/MultiMarkdown propose here https://fletcher.github.io/MultiMarkdown-4/tables.html

``` md
| Head 1  | Head 2  | Head 3  |
| ------- | ------- | ------- |
| cel 1 a | cel 2 a | cel 3 a |
| cel 1 b | cel 2 b | cel 3 b |
[Caption Text][table-id]
```

**Comment by hason** [comment]
Added in [0.5.0](https://github.com/webuni/commonmark-table-extension/releases/tag/0.5.0)
