### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark-ext-table#32]
I'm thinking of bringing all of the "official" League extensions into the main library so that everyone can use things like tables out-of-the-box without needing additional packages.  This will make it MUCH easier to test extension compatibility each time we release a new version of `league/commonmark` too.

To do this, we'd probably want to change the license of this library from MIT to BSD-3-Clause so that everything is using the same license.

@hason What are your thoughts on this?

**Comment by hason** [comment]
I do not have a problem with it.

**Comment by colinodell** [comment]
Thanks!
